version: '3.8'

services:
  kodero:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kodero-game
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "com.example.description=Kodero Visual Programming Game"
      - "com.example.version=1.0.0"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s