version: '3.8'

services:
  kodero-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: kodero-game-dev
    ports:
      - "5173:5173"
    volumes:
      # Mount source code for hot-reload
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      # Prevent node_modules from being overwritten
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true